FROM factoriotools/factorio:1.1.110

COPY config /opt/factorio/config
COPY config /factorio/config
COPY mods /opt/factorio/mods
COPY scenarios /opt/factorio/scenarios

EXPOSE 34197/udp
EXPOSE 27015/tcp

USER factorio